#.kitchen.yml
driver:
  name: ec2
  region: eu-west-2
  instance_type: t3.small
  spot_price: on-demand

platforms:
  - name: ubuntu-20.04

provisioner:
  name: shell
  script: 'test/scripts/setup.sh'
  root_path: '/home/ubuntu/'
  data_path: '.'

suites:
  - name: default
    verifier:
      name: inspec
      inspec_tests:
        - test/integration/default
