#!/bin/bash
set -e

error() {
    local parent_lineno="$1"
    local message="$2"
    local code="${3:-1}"
    if [[ -n "$message" ]] ; then
        echo "Error on or near line ${parent_lineno}: ${message}; exiting with status ${code}"
    else
        echo "Error on or near line ${parent_lineno}; exiting with status ${code}"
    fi
    exit "${code}"
}
trap 'error ${LINENO}' ERR

function echo_task() {
    echo -e " \e[33m*\e[39m $1"
}

function echo_sub_task() {
    echo -e "   \e[33m*\e[39m $1"
}

function check_apt_installed() {
    return dpkg -l "$1" &> /dev/null
}
function apt_install() {
    if dpkg --get-selections | grep -q "^$1[[:space:]]*install$" >/dev/null; then
        echo_sub_task "$1 already installed"
    else
        echo_sub_task "Installing $1"
        sudo apt-get -qq install -y "$1"
    fi
}

function is_sudo() {
    if groups | grep -q "\\bsudo\b"; then
        return 0
    fi
    return 1
}

WARNS=()
function add_warn() {
    WARNS+=("$1")
}
function display_warns() {
    if [ ${#WARNS[@]} -gt 0 ]; then
        echo -e "\n\n\e[93mWARNING:\e[39m"
        for warn in "${WARNS[@]}"
        do
            echo -e " \e[33m*\e[39m $WARNS"
        done
    fi
}

# --------------------------------------------------

REPO=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo "Running dotfiles setup"
echo "----------------------------------------------------------------------------------------------------------------------"
echo ""
echo -e "             \e[94m||||||||||||"
echo -e "             \e[34m88\e[94m||||||||||||"
echo -e "             \e[34m8888\e[94m||||||||||||"
echo -e "             \e[34m888888\e[94m||||||||||||"
echo -e "             \e[34m88888888\e[94m||||||||||||"
echo -e "             \e[34m8888888888\e[94m||||||||||||"
echo -e "             \e[34m888888888888\e[94m||||||||||||"
echo -e "             \e[94m|||||||||||||\e[34m888888888888"
echo -e "  \e[94m||         \e[34m8\e[94m||||||||||||||\e[34m88888888          \e[34mUser:\e[39m           $(whoami)"
echo -e "  \e[94m||||       \e[34m888\e[94m||||||||||||||\e[34m8888            \e[34mHostname:\e[39m       $(hostname)"
echo -e "  \e[94m||||||     \e[34m88888\e[94m|||||||||||||\e[34m8              \e[34mDistro:\e[39m         $(lsb_release -si) $(lsb_release -sr)"
echo -e "  \e[94m||||||||   \e[34m8888888\e[94m|||||||||||||             \e[34mKernel:\e[39m         $(uname -r)"
echo -e "  \e[94m|||||||||  \e[34m888888888\e[94m||||||||||||||          \e[34mShell:\e[39m          $SHELL"
echo -e "  \e[94m|||||||||||\e[34m88888888888\e[94m||||||||||||||        \e[34mCPU:\e[39m            $(sed -n 's/^model name[ \t]*: *//p' /proc/cpuinfo | uniq | sed ':a;N;$!ba;s/\n/, /g')"
echo -e "  \e[94m|||||||||||\e[34m8888888888888\e[94m||||||||||||        \e[34mHome directory:\e[39m $HOME"
echo -e "   \e[94m||||||||||||\e[34m888888888888\e[94m||||||||||||       \e[34mDotfiles:\e[39m       $REPO"
echo -e "     \e[94m||||||||||||\e[34m8888888888  \e[94m||||||||||       \e[34mSudo:\e[39m           $(if is_sudo -eq 0; then echo 'Yes'; else echo 'No'; fi)"
echo -e "       \e[94m||||||||||||\e[34m88888888   \e[94m|||||||||"
echo -e "         \e[94m||||||||||||\e[34m888888     \e[94m|||||||"
echo -e "           \e[94m||||||||||||\e[34m8888       \e[94m|||||"
echo -e "             \e[94m||||||||||||\e[34m88         \e[94m|||"
echo -e "               \e[94m||||||||||||          \e[94m||\e[39m"
echo ""
echo "---------------------------------------------------------------------------------------------------------------------"
echo ""
echo ""


echo "Executing tasks:"


# Submodules
echo_task "Updating submodules"
git --git-dir="$REPO/.git" submodule init
git --git-dir="$REPO/.git" submodule update


# apt packages
if command -v apt-get > /dev/null; then
    echo_task "Installing apt packages"
    apt_install "curl"
    apt_install "htop"
    apt_install "python"
    apt_install "python-pip"
    apt_install "python3"
    apt_install "python3-pip"
    apt_install "tmux"
    apt_install "vim"
else
    echo_task "Skipping apt packages"
fi


# gnupg
echo_task "Setting up gnupg config"
mkdir -p "$HOME/.gnupg"
ln -sf "$REPO/gnupg/gpg.conf" "$HOME/.gnupg/gpg.conf"
ln -sf "$REPO/gnupg/scd-event" "$HOME/.gnupg/scd-event"
chmod +x "$HOME/.gnupg/scd-event"


# VIM
echo_task "Setting up VIM config"
ln -sf "$REPO/vim/.vimrc" "$HOME/.vimrc"


# TMUX
echo_task "Setting up TMUX config"
ln -sf "$REPO/tmux/.tmux.conf" "$HOME/.tmux.conf"
if [ -z "$HOME/.tmux/plugins/tpm" ]; then
	git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi


# Local ~/bin
echo_task "Setup local bin"
mkdir -p "$HOME/bin"
for f in $REPO/bin/*
do
	bin_filename=$(basename "$f")
	echo_sub_task "$bin_filename"
	ln -sf "$REPO/bin/$bin_filename" "$HOME/bin/$bin_filename"
done
for f in $REPO/scripts/bin/*
do
        bin_filename=$(basename "$f")
        echo_sub_task "$bin_filename"
        ln -sf "$REPO/scripts/bin/$bin_filename" "$HOME/bin/$bin_filename"
done


# ZSH
echo_task "Setting up ZSH"
if check_apt_installed "fonts-powerline"; then
    echo_sub_task "Installing powerline fonts"
    sudo apt-get install -y -q fonts-powerline
    echo_sub_task "Re-building font cache"
    fc-cache -f
fi


# oh-my-zsh
if [ -d "$HOME/.oh-my-zsh" ]; then
	echo_sub_task "oh-my-zsh already installed"
else
	echo_sub_task "Installing oh-my-zsh"
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" || [ -d "$HOME/.oh-my-zsh" ]
fi
cp -r "$REPO/zsh/custom" "$HOME/.oh-my-zsh/"
cp "$REPO/zsh/.zshrc" "$HOME/.zshrc"
cp "$REPO/zsh/.zshenv" "$HOME/.zshenv"


# Git
echo_task "Setting up git"
git config --global user.name "James Ridgway"
git config --global core.editor vim  &> /dev/null
git config --global push.default current &> /dev/null


# Gnome
if command -v gsettings > /dev/null; then
    echo_task "Setting up gnome"
    gsettings set org.gnome.nautilus.preferences default-folder-viewer "list-view"
else
    echo_task "Skipping gnome setup"
fi


# Terminator
echo_task "Setting up terminator"
mkdir -p "${HOME}/.config/terminator"
cp "$REPO/terminator/config" "$HOME/.config/terminator/config"


# Powerline
powerline_path=$(python3 -c 'import pkgutil; print(pkgutil.get_loader("powerline").get_filename())' || true)
if [[ "$powerline_path" != "" ]]; then
	echo_task "Powerline already installed"
else
	echo_task "Setup powerline"
	pip install --user git+git://github.com/powerline/powerline | sed 's/^/      /'
	pip3 install --user git+git://github.com/powerline/powerline | sed 's/^/      /'
fi
ln -sf "$REPO/config/powerline" "$HOME/.config/powerline"


# Install AWS CLI
if pip freeze | grep -q "awscli"; then
    echo_task "awscli already installed"
else
    echo_task "Install awscli"
    pip3 install --user awscli | sed 's/^/      /'
fi


# SSH Config
if [ -f "$HOME/.aws/credentials" ]; then
    echo_task "Applying SSH config"
    ssh-config --apply  2>&1 | sed 's/^/      /'
else
    add_warn "SSH config not applied because awscli is not installed and/or AWS credentials do not exist."
fi

# Gradle
echo_task "Setting up gradle"
mkdir -p "$HOME/.gradle"
ln -sf "$REPO/gradle/gradle.properties" "$HOME/.gradle/gradle.properties"


# End script, display any warnings
display_warns
echo -e "\n\e[32mSetup complete\e[39m"