-- Host-specific Hyprland settings for jamesp1.
-- Loaded from hypr/monitors.lua via require_optional, so this file is only
-- picked up on the machine whose hostname matches its name.
--
-- Monitor geometry does NOT belong here. Put a panel's scale in monitors.lua,
-- so that Omarchy's scaling tools can find and rewrite it. This file is for
-- settings that are global and cannot be expressed per-output.
--
-- GDK_SCALE used to live here. It moved to monitors.lua as omarchy_gdk_scale,
-- because omarchy-hyprland-monitor-scaling rewrites it together with the
-- monitor scale. Setting it in both files would leave this copy stale.

-- (no host-specific settings at present)
